### ISSUE TITLE
Allow fraction with 0/0

### ISSUE THREAD

**Issue by jbrucker** [ISP19/unittesting-llleyelll#1]
Your test cases look good, but please change
the behavior for Fraction(0, 0).

Since we allow 1/0 and -1/0, we should also
allow 0/0.  All three are considered "extended numbers".
0/0 is NaN (not a number).  1/0 is Infinity.
I want your Fraction class to permit extended
numbers, even if the arithmetic operations don't
work correctly for +/-Infinity and NaN.

So instead of an error, just allow `Fraction(0,0)`
as a valid fraction, and `__str__` returns it as "0/0".

**Comment by llleyelll** [comment]
I fixed that problem and my program already work fine with 1/0, -1/0, and 0/0

**Comment by chiiida** [comment]
I fixed that problem and my program already work fine with 1/0, -1/0, and 0/0
Thank you for your suggestion.
